import { describe, expect, it } from "vitest";
import { STALE_MS, SCORE_SCHEMA, ScoreFollower, parseScore } from "./score-live";

const healthy = { rate: 4, burstiness: 0.1, template_entropy: 2, fan_out: 3, anomaly_z: 0.2, health: 1 };

function doc(frames: Array<{ index: number; nodes: Record<string, unknown> }>, schema = SCORE_SCHEMA) {
  return { schema, rate_hz: 10, provider: "logswarm", fields: [], nodes: [], frames: frames.map((f) => ({ t: f.index / 10, ...f })) };
}

describe("parseScore", () => {
  it("reads the archived score.json shape, which is also the live one", () => {
    const frames = parseScore(doc([{ index: 3, nodes: { api: healthy } }]));
    expect(frames?.[0]?.nodes.get("api")).toEqual(healthy);
  });

  it("rejects another schema whole, because every number would mean something else", () => {
    expect(parseScore(doc([{ index: 1, nodes: { api: healthy } }], "orchard/score/2"))).toBeNull();
    expect(parseScore(null)).toBeNull();
    expect(parseScore({ schema: SCORE_SCHEMA })).toBeNull();
  });

  it("drops only the unreadable node, not the frame", () => {
    const frames = parseScore(doc([{ index: 1, nodes: { api: healthy, db: { ...healthy, rate: "fast" } } }]));
    expect([...frames![0]!.nodes.keys()]).toEqual(["api"]);
  });

  it("orders frames by index whatever order they were published in", () => {
    const frames = parseScore(doc([{ index: 9, nodes: {} }, { index: 7, nodes: {} }]));
    expect(frames?.map((f) => f.index)).toEqual([7, 9]);
  });
});

describe("ScoreFollower", () => {
  it("takes the newest frame of a window", () => {
    const f = new ScoreFollower();
    expect(f.ingest(doc([{ index: 1, nodes: { api: { ...healthy, rate: 1 } } }, { index: 2, nodes: { api: healthy } }]), 0)).toBe(true);
    expect(f.state("api", 0)).toEqual(healthy);
  });

  it("does not move backwards when a poll returns an older window", () => {
    // A CDN edge or a retry can hand back a window that is behind.
    const f = new ScoreFollower();
    f.ingest(doc([{ index: 20, nodes: { api: healthy } }]), 0);
    expect(f.ingest(doc([{ index: 19, nodes: { api: { ...healthy, rate: 99 } } }]), 100)).toBe(false);
    expect(f.state("api", 100)).toEqual(healthy);
  });

  it("starts over when the provider restarts its count", () => {
    const f = new ScoreFollower();
    f.ingest(doc([{ index: 5000, nodes: { api: healthy } }]), 0);
    expect(f.ingest(doc([{ index: 2, nodes: { api: { ...healthy, rate: 7 } } }]), 100)).toBe(true);
    expect(f.state("api", 100)?.rate).toBe(7);
  });

  it("goes silent when the feed stops, instead of holding a note forever", () => {
    const f = new ScoreFollower();
    f.ingest(doc([{ index: 1, nodes: { api: healthy } }]), 1000);
    expect(f.state("api", 1000 + STALE_MS)).not.toBeNull();
    expect(f.state("api", 1000 + STALE_MS + 1)).toBeNull();
    expect(f.stale(1000 + STALE_MS + 1)).toBe(true);
  });

  it("silences a node missing from the newest frame", () => {
    const f = new ScoreFollower();
    f.ingest(doc([{ index: 1, nodes: { api: healthy, db: healthy } }]), 0);
    f.ingest(doc([{ index: 2, nodes: { api: healthy } }]), 10);
    expect(f.state("db", 10)).toBeNull();
  });

  it("counts versions only for newer frames", () => {
    const f = new ScoreFollower();
    f.ingest(doc([{ index: 1, nodes: {} }]), 0);
    f.ingest(doc([{ index: 1, nodes: {} }]), 5);
    expect(f.version).toBe(1);
  });
});

describe("the contract with packages/score", () => {
  it("reads a window written by the real LiveScoreWriter", async () => {
    // fixtures/score.live.json is generated by orchard_score.LiveScoreWriter
    // (window 3, five frames written). If either side changes the bytes, this
    // fails here rather than in a room that has gone silent.
    const { readFileSync } = await import("node:fs");
    const doc: unknown = JSON.parse(readFileSync(new URL("./fixtures/score.live.json", import.meta.url), "utf8"));
    const f = new ScoreFollower();
    expect(f.ingest(doc, 0)).toBe(true);
    expect(f.state("api", 0)?.rate).toBe(6);
    expect(f.state("db", 0)?.health).toBe(0.5);
  });
});
