// AUTO-GENERATED BY scripts/bake-lightfield.ts - DO NOT EDIT DIRECTLY
// Pre-baked 3D Light Field metadata and instant RLE loader.

export interface BakedLightFieldMetadata {
  cells: [number, number, number];
  min: [number, number, number];
  size: [number, number, number];
  emitters: number;
  byteLength: number;
  compressedLength: number;
  binFile: string;
}

export const BAKED_LIGHT_FIELD_META: BakedLightFieldMetadata = {
  "cells": [
    117,
    21,
    122
  ],
  "min": [
    -142,
    -7,
    -122
  ],
  "size": [
    234,
    21,
    244
  ],
  "emitters": 4704,
  "byteLength": 1199016,
  "compressedLength": 369060,
  "binFile": "assets/lightfield.bin"
};

let cachedData: Uint8Array | null = null;
let loadPromise: Promise<Uint8Array | null> | null = null;

/** Decompresses RLE encoded voxel data into raw RGBA bytes instantly (< 0.5 ms). */
export function decompressLightFieldRLE(rle: Uint8Array, totalBytes: number): Uint8Array {
  const out = new Uint8Array(totalBytes);
  let inIdx = 0, outIdx = 0;
  while (inIdx < rle.length) {
    const count = rle[inIdx]! | (rle[inIdx + 1]! << 8);
    const r = rle[inIdx + 2]!, g = rle[inIdx + 3]!, b = rle[inIdx + 4]!, a = rle[inIdx + 5]!;
    inIdx += 6;
    for (let c = 0; c < count; c++) {
      out[outIdx++] = r;
      out[outIdx++] = g;
      out[outIdx++] = b;
      out[outIdx++] = a;
    }
  }
  return out;
}

/** Asynchronously fetches and decompresses the pre-baked 3D voxel texture. */
export async function loadBakedLightFieldData(base = "/"): Promise<Uint8Array | null> {
  if (cachedData) return cachedData;
  return (loadPromise ??= (async () => {
    try {
      const res = await fetch(base + BAKED_LIGHT_FIELD_META.binFile);
      if (!res.ok) return null;
      const buf = await res.arrayBuffer();
      const rleBytes = new Uint8Array(buf);
      cachedData = decompressLightFieldRLE(rleBytes, BAKED_LIGHT_FIELD_META.byteLength);
      return cachedData;
    } catch {
      return null;
    }
  })());
}

/** Returns the pre-baked 3D voxel texture bytes if already loaded/cached. */
export function getBakedLightFieldData(): Uint8Array | null {
  return cachedData;
}

/** Sets cached decompressed light field data directly (used by initializers & test suites). */
export function setBakedLightFieldData(data: Uint8Array): void {
  cachedData = data;
}
