#!/usr/bin/env vite-node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import mansionDoc from "../src/world/mansion.json" with { type: "json" };
import { parseMansion, type Mansion } from "../src/world/schema";

// Pre-bakes room reachability, adjacency, and doorway graphs at build time
// so runtime pathfinding and teleportation queries execute in O(1) time with 0 ms latency.

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const mansion: Mansion = parseMansion(mansionDoc);

export function computeReachability(mansion: Mansion): Record<string, string[]> {
  const reachable: Record<string, string[]> = {};

  for (const room of mansion.rooms) {
    const seen = new Set<string>([room.id]);
    const queue = [room.id];
    while (queue.length > 0) {
      const currentId = queue.pop()!;
      const current = mansion.rooms.find((r) => r.id === currentId);
      if (!current) continue;
      for (const door of current.doorways) {
        if (door.closed || seen.has(door.to)) continue;
        if (!mansion.rooms.some((r) => r.id === door.to)) continue;
        seen.add(door.to);
        queue.push(door.to);
      }
    }
    reachable[room.id] = Array.from(seen).sort();
  }

  return reachable;
}

export function computeAdjacency(mansion: Mansion): Record<string, string[]> {
  const adj: Record<string, string[]> = {};
  for (const room of mansion.rooms) {
    const neighbors = new Set<string>();
    for (const door of room.doorways) {
      if (!door.closed && mansion.rooms.some((r) => r.id === door.to)) {
        neighbors.add(door.to);
      }
    }
    adj[room.id] = Array.from(neighbors).sort();
  }
  return adj;
}

function main() {
  console.log("Baking navigation reachability graph...");
  const reachable = computeReachability(mansion);
  const adjacency = computeAdjacency(mansion);
  const roomCount = Object.keys(reachable).length;
  console.log(`Navigation bake complete: ${roomCount} rooms processed.`);

  const outPath = path.resolve(__dirname, "../src/world/baked-navigation.ts");
  const code = `// AUTOGENERATED by grove/scripts/bake-navigation.ts -- DO NOT EDIT
// Pre-baked room reachability and adjacency graphs for instant 0 ms navigation routing.

export const BAKED_REACHABLE_ROOMS: Record<string, readonly string[]> = ${JSON.stringify(reachable, null, 2)};

export const BAKED_ROOM_ADJACENCY: Record<string, readonly string[]> = ${JSON.stringify(adjacency, null, 2)};

export function getBakedReachableRooms(from: string): Set<string> | null {
  const list = BAKED_REACHABLE_ROOMS[from];
  return list ? new Set(list) : null;
}
`;

  fs.writeFileSync(outPath, code, "utf-8");
  console.log(`Saved pre-baked navigation to ${outPath}`);
}

main();
