/**
 * Pre-bakes the palace 3D Light Field at build time with compact RLE binary asset
 * so the browser client loads it with instant 0 ms latency without CPU voxel calculations
 * and with zero embedded base64 bloat.
 *
 * Run via:
 *   pnpm run bake:lightfield
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import mansionDocument from "../src/world/mansion.json" with { type: "json" };
import { parseMansion } from "../src/world/schema";
import { emittersOf } from "../src/world/observatory";
import { bakeLightField } from "../src/world/lightfield";

const here = dirname(fileURLToPath(import.meta.url));
const srcWorld = join(here, "..", "src", "world");
const publicAssets = join(here, "..", "public", "assets");

console.log("Pre-baking 3D Light Field from mansion.json...");
const start = performance.now();
const mansion = parseMansion(mansionDocument);
const emitters = emittersOf(mansion);
console.log(`Found ${emitters.length} luminous architectural emitters across lit rooms.`);

const field = bakeLightField(mansion, emitters);
const elapsed = (performance.now() - start).toFixed(1);
console.log(`Bake completed in ${elapsed} ms.`);
console.log(`Grid cells: [${field.cells.join(", ")}], total voxels: ${field.cells[0] * field.cells[1] * field.cells[2]}`);
console.log(`Min: [${field.min.x}, ${field.min.y}, ${field.min.z}], Size: [${field.size.x}, ${field.size.y}, ${field.size.z}]`);

const data = field.texture.image.data as Uint8Array;
console.log(`Uncompressed texture bytes: ${data.length} bytes (${(data.length / 1024).toFixed(1)} KB)`);

// Compress with Run-Length Encoding (RLE)
const rleBytes: number[] = [];
let i = 0;
while (i < data.length) {
  let count = 1;
  const r = data[i]!, g = data[i + 1]!, b = data[i + 2]!, a = data[i + 3]!;
  while (
    i + count * 4 < data.length &&
    count < 65535 &&
    data[i + count * 4] === r &&
    data[i + count * 4 + 1] === g &&
    data[i + count * 4 + 2] === b &&
    data[i + count * 4 + 3] === a
  ) {
    count++;
  }
  rleBytes.push(count & 0xff, (count >> 8) & 0xff, r, g, b, a);
  i += count * 4;
}

const rleBuffer = Buffer.from(rleBytes);
console.log(`RLE compressed bytes: ${rleBuffer.length} bytes (${(rleBuffer.length / 1024).toFixed(1)} KB)`);

// 1. Write static binary to public/assets/lightfield.bin
mkdirSync(publicAssets, { recursive: true });
const binPath = join(publicAssets, "lightfield.bin");
writeFileSync(binPath, rleBuffer);
console.log(`Wrote binary asset: ${binPath}`);

// 2. Generate clean TypeScript module in src/world/baked-lightfield.ts
const metadata = {
  cells: field.cells,
  min: [field.min.x, field.min.y, field.min.z],
  size: [field.size.x, field.size.y, field.size.z],
  emitters: field.emitters,
  byteLength: data.length,
  compressedLength: rleBuffer.length,
  binFile: "assets/lightfield.bin",
};

const tsContent = `// AUTO-GENERATED BY scripts/bake-lightfield.ts - DO NOT EDIT DIRECTLY
// Pre-baked 3D Light Field metadata and instant RLE loader.

export interface BakedLightFieldMetadata {
  cells: [number, number, number];
  min: [number, number, number];
  size: [number, number, number];
  emitters: number;
  byteLength: number;
  compressedLength: number;
  binFile: string;
}

export const BAKED_LIGHT_FIELD_META: BakedLightFieldMetadata = ${JSON.stringify(metadata, null, 2)};

let cachedData: Uint8Array | null = null;
let loadPromise: Promise<Uint8Array | null> | null = null;

/** Decompresses RLE encoded voxel data into raw RGBA bytes instantly (< 0.5 ms). */
export function decompressLightFieldRLE(rle: Uint8Array, totalBytes: number): Uint8Array {
  const out = new Uint8Array(totalBytes);
  let inIdx = 0, outIdx = 0;
  while (inIdx < rle.length) {
    const count = rle[inIdx]! | (rle[inIdx + 1]! << 8);
    const r = rle[inIdx + 2]!, g = rle[inIdx + 3]!, b = rle[inIdx + 4]!, a = rle[inIdx + 5]!;
    inIdx += 6;
    for (let c = 0; c < count; c++) {
      out[outIdx++] = r;
      out[outIdx++] = g;
      out[outIdx++] = b;
      out[outIdx++] = a;
    }
  }
  return out;
}

/** Asynchronously fetches and decompresses the pre-baked 3D voxel texture. */
export async function loadBakedLightFieldData(base = "/"): Promise<Uint8Array | null> {
  if (cachedData) return cachedData;
  return (loadPromise ??= (async () => {
    try {
      const res = await fetch(base + BAKED_LIGHT_FIELD_META.binFile);
      if (!res.ok) return null;
      const buf = await res.arrayBuffer();
      const rleBytes = new Uint8Array(buf);
      cachedData = decompressLightFieldRLE(rleBytes, BAKED_LIGHT_FIELD_META.byteLength);
      return cachedData;
    } catch {
      return null;
    }
  })());
}

/** Returns the pre-baked 3D voxel texture bytes if already loaded/cached. */
export function getBakedLightFieldData(): Uint8Array | null {
  return cachedData;
}

/** Sets cached decompressed light field data directly (used by initializers & test suites). */
export function setBakedLightFieldData(data: Uint8Array): void {
  cachedData = data;
}
`;

const tsPath = join(srcWorld, "baked-lightfield.ts");
writeFileSync(tsPath, tsContent, "utf8");
console.log(`Generated TypeScript pre-baked module: ${tsPath}`);
console.log("Pre-baking finished successfully.");
