// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tree: __t.string().primaryKey(),
  repo: __t.string(),
  commit: __t.string(),
  licence: __t.string(),
  plan: __t.string(),
  state: __t.string(),
  hostPaused: __t.bool().name("host_paused"),
  linkedBy: __t.identity().name("linked_by"),
  linkedAt: __t.timestamp().name("linked_at"),
  confirmedAt: __t.timestamp().name("confirmed_at"),
});
