// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  tree: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  url: __t.string(),
  thumbUrl: __t.string().name("thumb_url"),
  tapeUrl: __t.string().name("tape_url"),
  hungAt: __t.timestamp().name("hung_at"),
});
