// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
  addedAt: __t.timestamp(),
});
export type Admin = __Infer<typeof Admin>;

export const Chat = __t.object("Chat", {
  id: __t.u64(),
  room: __t.string(),
  sender: __t.identity(),
  name: __t.string(),
  text: __t.string(),
  at: __t.timestamp(),
});
export type Chat = __Infer<typeof Chat>;

export const Directive = __t.object("Directive", {
  id: __t.u64(),
  text: __t.string(),
  active: __t.bool(),
  at: __t.timestamp(),
});
export type Directive = __Infer<typeof Directive>;

export const Exhibit = __t.object("Exhibit", {
  id: __t.u64(),
  tree: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  url: __t.string(),
  thumbUrl: __t.string(),
  tapeUrl: __t.string(),
  hungAt: __t.timestamp(),
});
export type Exhibit = __Infer<typeof Exhibit>;

export const Pose = __t.object("Pose", {
  identity: __t.identity(),
  room: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Pose = __Infer<typeof Pose>;

export const ReviewItem = __t.object("ReviewItem", {
  id: __t.u64(),
  tree: __t.string(),
  thesis: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  url: __t.string(),
  note: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type ReviewItem = __Infer<typeof ReviewItem>;

export const Room = __t.object("Room", {
  name: __t.string(),
  title: __t.string(),
  adminOnly: __t.bool(),
  open: __t.bool(),
  capacity: __t.u32(),
});
export type Room = __Infer<typeof Room>;

export const Ruling = __t.object("Ruling", {
  id: __t.u64(),
  reviewId: __t.u64(),
  verdict: __t.string(),
  note: __t.string(),
  by: __t.identity(),
  at: __t.timestamp(),
});
export type Ruling = __Infer<typeof Ruling>;

export const Snapshot = __t.object("Snapshot", {
  key: __t.string(),
  json: __t.string(),
  at: __t.timestamp(),
});
export type Snapshot = __Infer<typeof Snapshot>;

export const Tree = __t.object("Tree", {
  name: __t.string(),
  question: __t.string(),
  status: __t.string(),
  stage: __t.string(),
  potential: __t.u8(),
  updatedAt: __t.timestamp(),
});
export type Tree = __Infer<typeof Tree>;

export const Visitor = __t.object("Visitor", {
  identity: __t.identity(),
  name: __t.string(),
  room: __t.string(),
  isAdmin: __t.bool(),
  online: __t.bool(),
  muted: __t.bool(),
  lastSeen: __t.timestamp(),
  lastSaid: __t.timestamp(),
});
export type Visitor = __Infer<typeof Visitor>;

