// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
  addedAt: __t.timestamp(),
});
export type Admin = __Infer<typeof Admin>;

export const Area = __t.object("Area", {
  tree: __t.string(),
  repo: __t.string(),
  commit: __t.string(),
  plan: __t.string(),
  state: __t.string(),
  hostPaused: __t.bool(),
  linkedBy: __t.identity(),
  linkedAt: __t.timestamp(),
  confirmedAt: __t.timestamp(),
});
export type Area = __Infer<typeof Area>;

export const AreaAdmin = __t.object("AreaAdmin", {
  id: __t.u64(),
  tree: __t.string(),
  identity: __t.identity(),
  addedBy: __t.identity(),
  addedAt: __t.timestamp(),
});
export type AreaAdmin = __Infer<typeof AreaAdmin>;

export const AreaSanction = __t.object("AreaSanction", {
  key: __t.string(),
  tree: __t.string(),
  identity: __t.identity(),
  muted: __t.bool(),
  until: __t.timestamp(),
  reason: __t.string(),
  by: __t.identity(),
  at: __t.timestamp(),
});
export type AreaSanction = __Infer<typeof AreaSanction>;

export const Ban = __t.object("Ban", {
  identity: __t.identity(),
  network: __t.string(),
  until: __t.timestamp(),
  reason: __t.string(),
  by: __t.identity(),
  at: __t.timestamp(),
});
export type Ban = __Infer<typeof Ban>;

export const Broadcast = __t.object("Broadcast", {
  id: __t.u64(),
  kind: __t.string(),
  cue: __t.string(),
  text: __t.string(),
  room: __t.string(),
  at: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type Broadcast = __Infer<typeof Broadcast>;

export const Chat = __t.object("Chat", {
  id: __t.u64(),
  room: __t.string(),
  sender: __t.identity(),
  name: __t.string(),
  text: __t.string(),
  at: __t.timestamp(),
});
export type Chat = __Infer<typeof Chat>;

export const ChatHere = __t.object("ChatHere", {});
export type ChatHere = __Infer<typeof ChatHere>;

export const Connection = __t.object("Connection", {
  id: __t.connectionId(),
  identity: __t.identity(),
  at: __t.timestamp(),
});
export type Connection = __Infer<typeof Connection>;

export const Directive = __t.object("Directive", {
  id: __t.u64(),
  text: __t.string(),
  active: __t.bool(),
  at: __t.timestamp(),
});
export type Directive = __Infer<typeof Directive>;

export const Exhibit = __t.object("Exhibit", {
  id: __t.u64(),
  tree: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  url: __t.string(),
  thumbUrl: __t.string(),
  tapeUrl: __t.string(),
  hungAt: __t.timestamp(),
});
export type Exhibit = __Infer<typeof Exhibit>;

export const Guest = __t.object("Guest", {
  identity: __t.identity(),
  network: __t.string(),
  seenAt: __t.timestamp(),
});
export type Guest = __Infer<typeof Guest>;

export const JoinThrottle = __t.object("JoinThrottle", {
  identity: __t.identity(),
  tokens: __t.f64(),
  at: __t.timestamp(),
});
export type JoinThrottle = __Infer<typeof JoinThrottle>;

export const PeopleHere = __t.object("PeopleHere", {});
export type PeopleHere = __Infer<typeof PeopleHere>;

export const Pose = __t.object("Pose", {
  identity: __t.identity(),
  room: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Pose = __Infer<typeof Pose>;

export const PosesHere = __t.object("PosesHere", {});
export type PosesHere = __Infer<typeof PosesHere>;

export const Report = __t.object("Report", {
  id: __t.u64(),
  reporter: __t.identity(),
  subject: __t.identity(),
  subjectName: __t.string(),
  room: __t.string(),
  reason: __t.string(),
  context: __t.string(),
  status: __t.string(),
  at: __t.timestamp(),
});
export type Report = __Infer<typeof Report>;

export const ReviewItem = __t.object("ReviewItem", {
  id: __t.u64(),
  tree: __t.string(),
  thesis: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  url: __t.string(),
  note: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type ReviewItem = __Infer<typeof ReviewItem>;

export const Room = __t.object("Room", {
  name: __t.string(),
  title: __t.string(),
  adminOnly: __t.bool(),
  open: __t.bool(),
  capacity: __t.u32(),
});
export type Room = __Infer<typeof Room>;

export const Ruling = __t.object("Ruling", {
  id: __t.u64(),
  reviewId: __t.u64(),
  verdict: __t.string(),
  note: __t.string(),
  by: __t.identity(),
  at: __t.timestamp(),
});
export type Ruling = __Infer<typeof Ruling>;

export const Setting = __t.object("Setting", {
  key: __t.string(),
  value: __t.string(),
});
export type Setting = __Infer<typeof Setting>;

export const Snapshot = __t.object("Snapshot", {
  key: __t.string(),
  json: __t.string(),
  at: __t.timestamp(),
});
export type Snapshot = __Infer<typeof Snapshot>;

export const SweepTimer = __t.object("SweepTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SweepTimer = __Infer<typeof SweepTimer>;

export const Throttle = __t.object("Throttle", {
  identity: __t.identity(),
  moveTokens: __t.f64(),
  moveAt: __t.timestamp(),
  reportAt: __t.timestamp(),
});
export type Throttle = __Infer<typeof Throttle>;

export const Tree = __t.object("Tree", {
  name: __t.string(),
  question: __t.string(),
  status: __t.string(),
  stage: __t.string(),
  potential: __t.u8(),
  updatedAt: __t.timestamp(),
});
export type Tree = __Infer<typeof Tree>;

export const Visitor = __t.object("Visitor", {
  identity: __t.identity(),
  name: __t.string(),
  room: __t.string(),
  isAdmin: __t.bool(),
  online: __t.bool(),
  muted: __t.bool(),
  lastSeen: __t.timestamp(),
  lastSaid: __t.timestamp(),
});
export type Visitor = __Infer<typeof Visitor>;

export const Whereabouts = __t.object("Whereabouts", {
  identity: __t.identity(),
  room: __t.string(),
});
export type Whereabouts = __Infer<typeof Whereabouts>;

