// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  room: __t.string(),
  isAdmin: __t.bool().name("is_admin"),
  online: __t.bool(),
  muted: __t.bool(),
  lastSeen: __t.timestamp().name("last_seen"),
  lastSaid: __t.timestamp().name("last_said"),
});
