// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAdminReducer from "../add_admin_reducer";
import BanVisitorReducer from "../ban_visitor_reducer";
import HangReducer from "../hang_reducer";
import JoinReducer from "../join_reducer";
import KickReducer from "../kick_reducer";
import LeaveReducer from "../leave_reducer";
import MoveReducer from "../move_reducer";
import MuteReducer from "../mute_reducer";
import PutSnapshotReducer from "../put_snapshot_reducer";
import RemoveTreeReducer from "../remove_tree_reducer";
import ReportVisitorReducer from "../report_visitor_reducer";
import ResolveReportReducer from "../resolve_report_reducer";
import RetireDirectiveReducer from "../retire_directive_reducer";
import RuleReducer from "../rule_reducer";
import SayReducer from "../say_reducer";
import SetAuthReducer from "../set_auth_reducer";
import SetDirectiveReducer from "../set_directive_reducer";
import SetRoomReducer from "../set_room_reducer";
import SubmitReviewReducer from "../submit_review_reducer";
import SweepNowReducer from "../sweep_now_reducer";
import TakeDownReducer from "../take_down_reducer";
import UnbanReducer from "../unban_reducer";
import UpsertTreeReducer from "../upsert_tree_reducer";

export type AddAdminParams = __Infer<typeof AddAdminReducer>;
export type BanVisitorParams = __Infer<typeof BanVisitorReducer>;
export type HangParams = __Infer<typeof HangReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type KickParams = __Infer<typeof KickReducer>;
export type LeaveParams = __Infer<typeof LeaveReducer>;
export type MoveParams = __Infer<typeof MoveReducer>;
export type MuteParams = __Infer<typeof MuteReducer>;
export type PutSnapshotParams = __Infer<typeof PutSnapshotReducer>;
export type RemoveTreeParams = __Infer<typeof RemoveTreeReducer>;
export type ReportVisitorParams = __Infer<typeof ReportVisitorReducer>;
export type ResolveReportParams = __Infer<typeof ResolveReportReducer>;
export type RetireDirectiveParams = __Infer<typeof RetireDirectiveReducer>;
export type RuleParams = __Infer<typeof RuleReducer>;
export type SayParams = __Infer<typeof SayReducer>;
export type SetAuthParams = __Infer<typeof SetAuthReducer>;
export type SetDirectiveParams = __Infer<typeof SetDirectiveReducer>;
export type SetRoomParams = __Infer<typeof SetRoomReducer>;
export type SubmitReviewParams = __Infer<typeof SubmitReviewReducer>;
export type SweepNowParams = __Infer<typeof SweepNowReducer>;
export type TakeDownParams = __Infer<typeof TakeDownReducer>;
export type UnbanParams = __Infer<typeof UnbanReducer>;
export type UpsertTreeParams = __Infer<typeof UpsertTreeReducer>;

